name: Compatibility Deployment

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compatibility-deployment:
    name: ci/compatibility-deployment
    uses: OpsNexusHQ/opsnexus-deployment/.github/workflows/ci-compatibility-deployment.yml@7ebdf79ace7ba4894bce10905dd8d03632e06f92
    with:
      pr_repo: opsnexus-dashboard
      pr_sha: ${{ github.event.pull_request.head.sha || github.sha }}
      base_manifest_sha: ${{ github.event.pull_request.base.sha || github.sha }}
