name: Compatibility Deployment

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compatibility-deployment:
    name: ci/compatibility-deployment
    uses: OpsNexusHQ/opsnexus-deployment/.github/workflows/ci-compatibility-deployment.yml@09fa80119f293b2dffe508a957c3a5f99b75509b
    with:
      pr_repo: opsnexus-dashboard
      pr_sha: ${{ github.event.pull_request.head.sha || github.sha }}
      base_manifest_sha: ${{ github.event.pull_request.base.sha || github.sha }}
